[build]
  command = "# no build needed for static site"
  publish = "."

[dev]
  command = "npx http-server -c-1 -p 8888"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Forms setup
[[plugins]]
  package = "@netlify/plugin-nextjs"
